language: python
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7
  - os: osx
    language: generic
    env: PYTHON=3.4
  - os: osx
    language: generic
    env: PYTHON=3.5
  - os: osx
    language: generic
    env: PYTHON=3.6
  - os: linux
    language: generic
    env: PYTHON=2.7
  - os: linux
    language: generic
    env: PYTHON=3.4
  - os: linux
    language: generic
    env: PYTHON=3.5
  - os: linux
    language: generic
    env: PYTHON=3.6
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$PYTHON" == "2.7" ]]; then wget
  http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
  else wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  -O miniconda.sh; fi else if [[ "$PYTHON" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$PYTHON numpy scipy
- source activate test-environment
- pip install -r dev-requirements.txt
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: "jmschreiber"
  password:
    secure: "DJZlYMOGZ8ng41Zy+EgLNe48J+J7O6oT99vnIgHLf+vh6NZFDDVFnPAEP2X0t+BD7wqyvUqpYz256mPgpYmciapCsPU3/Y7+vGuX+Hyn9WnHadc5bzsCRnCsmbJQUPXjADlFD/lJil5FvKipUET/vCN+curDQUVtPHWpGMrxtp0="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
